server:
  port: ${PORT:9000}

file:
  upload-dir=upload-dir

spring:
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB

database:
  users:
    - id: 1
      name: namakao
      email: namakao@gmail.com
      events:

  events:
    - id: 1
      title: Pieskowi jest smutno :((
      address: Przytkowice 34-141
      description: takiemu o pieskowi jest bardzo smutno
      pictures:
        - id: 1
          path: http://localhost:9000/images/piesek.jpg
        - id: 2
          path: http://localhost:9000/images/piesek2.jpg
    - id: 2
      title: Temu tez smutno :((
      address: Krakow 30-392
      description: ojej :(
      pictures:
        - id: 1
          path: http://localhost:9000/images/piesek.jpg
        - id: 2
          path: http://localhost:9000/images/piesek2.jpg

  pictures:
    - id: 1
      path: http://localhost:9000/images/piesek.jpg
    - id: 2
      path: http://localhost:9000/img/petpatrol.png

